# Algortihm Parameters
alpha: 0.1
gamma: 0.8
epsilon: 0.9
epsilon_discount: 0.999 # 1098 eps to reach 0.1
nepisodes: 10
nsteps: 100

# Environment Parameters
desired_poses:
    x1: -1.6
    y1: 2.90 
    z1: 2.0 
    x2: 2.5 
    y2: -1.2 
    z2: 2.0 
    x3: 5.7 
    y3: 3.1 
    z3: 2.0 
    x4: 2.6 
    y4: 6.1 
    z4: 2.0

max_altitude: 2.8   # in meters
max_incl: 0.7       # in rads
speed_value: 1.0    # in m/s
running_step: 0.3   # in seconds
min_x: -2.5
max_x: 6
min_y: -2.5
max_y: 7

forward_reward: 20
turn_reward: 3
up_reward: 1
down_reward: 1
goal_reward: 200




